version: "3.9"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      # These are the credentials for the pgAdmin web UI login, NOT the DB
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      # Access pgAdmin web UI at http://localhost:5050
      - "5050:80"
    depends_on:
      - postgres
      # Connect postgres by using: 
      # name: ShopZada
      # hostname: postgres
      # port: 5432 
      # database: airflow
      # username: airflow
      # password: airflow

  airflow-init:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
    entrypoint: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname Air --lastname Flow --role Admin --email admin@example.com --password admin"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_files:/data_files
      - ./scripts:/scripts
      - ./sql:/sql
      - ./workflows:/workflows
      - ./clean_data:/clean_data

  airflow-webserver:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
    ports:
      - "8999:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_files:/data_files
      - ./scripts:/scripts
      - ./sql:/sql
      - ./workflows:/workflows
      - ./clean_data:/clean_data

  airflow-scheduler:
    build:
      context: .
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW_CONN_POSTGRES_DEFAULT: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_files:/data_files
      - ./scripts:/scripts
      - ./sql:/sql
      - ./workflows:/workflows
      - ./clean_data:/clean_data

volumes:
  postgres-db-volume:
